name: release

on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: [canary, stable]
    types:
      - completed

permissions:
  contents: write

jobs:
  create-release-dashboard:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Creates build
        working-directory: ./dashboard
        run: make release
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: dashboard-release-artifact
          retention-days: 1
          path: ./dashboard/target/sid2-dashboard.tar.gz
  create-release-keycloak-spi:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ./keycloak-radius-spi/maven-local-repo
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and test
        working-directory: ./keycloak-radius-spi
        run: make build
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: spi-release-artifact
          retention-days: 1
          path: ./keycloak-radius-spi/target/keycloak-radius-spi-jar-with-dependencies.jar
  create-release-landing-page:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Creates build
        working-directory: ./sid-landing-site
        run: make release
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: landing-page-release-artifact
          retention-days: 1
          path: ./sid-landing-site/target/sid2-landing-site.tar.gz
  make-logical-release:
    runs-on: ubuntu-latest
    needs: [create-release-keycloak-spi, create-release-dashboard, create-release-landing-page]
    name: Making release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      - name: Read .node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .node-version)
        id: get_node_version
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get_node_version.outputs.NODE_VERSION }}
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: |
          mkdir -p ./target
          npm install
      - uses: actions/download-artifact@v2
        with:
          path: ./target
      - name: Run release
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" = "stable" ]; then
            PREVIOUS_TAG="$(git tag --list --merged |egrep '^[0-9]{4}\.[0-1]?[0-9]\.[0-9]+$' |tail -n 1)"
            CONFIG_ARG="--config='.release-it.json'"
            # we have to pass skipUnstable on stable builds because dev build tags do not follow the same versioning as stable build tags and this causes commit messages to be formatted out of order
            SKIP_UNSTABLE_ARG="--'plugins.@release-it/conventional-changelog.skipUnstable'='true'"
          else
            PREVIOUS_TAG="$(git tag --list --merged |egrep '^[0-9]{4}\.[0-1]?[0-9]\.[0-9]+-dev\.1$' |tail -n 1)"
            CONFIG_ARG="--config='.release-it-dev.json'"
            SKIP_UNSTABLE_ARG=''
          fi
          # we have to pass plugins.@release-it/conventional-changelog.gitRawCommitOpts because tagMatch does not work the same in @release-it/conventional-changelog as in the default release-it changelog generator, per https://github.com/release-it/conventional-changelog/pull/47
          npm run release -- ${CONFIG_ARG} --git.tagMatch="${PREVIOUS_TAG}" --github.tagMatch="${PREVIOUS_TAG}" --'plugins.@release-it/conventional-changelog.gitRawCommitsOpts.from'="${PREVIOUS_TAG}" ${SKIP_UNSTABLE_ARG} --ci
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
